twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        an_example_of_a_global_variable: 'TODO: Move the global variables from the init_templates file to this location.'
        menu: '@App\Service\MenuService'

when@test:
    twig:
        strict_variables: true
