twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        version: '26.05.12'

when@test:
    twig:
        strict_variables: true
