# docker-compose.yaml
version: '3'

services :
  php:
    container_name: php.plb 
    build: 
      context: ./
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www
    environment:
      APP_ENV: dev
    working_dir: /var/www

  nginx:
    container_name: nginx.plb
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/planningbiblio.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    links:
      - php

  mariadb:
    container_name: mariadb.plb
    image: mariadb:10.3.9
    volumes:
        - ./data/:/var/lib/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: biblibre
        MYSQL_DATABASE: planningbiblio
        MYSQL_USER: planningbadmin
        MYSQL_PASSWORD: DEVplb21