<?php
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '10' WHERE `nom` = 'Multisites-nombre';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '20', `commentaires` = 'Nom du site N°1' WHERE `nom` = 'Multisites-site1';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '30', `commentaires` = 'Nom du site N°2' WHERE `nom` = 'Multisites-site2';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '40', `commentaires` = 'Nom du site N°3' WHERE `nom` = 'Multisites-site3';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '50', `commentaires` = 'Nom du site N°4' WHERE `nom` = 'Multisites-site4';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '60', `commentaires` = 'Nom du site N°5' WHERE `nom` = 'Multisites-site5';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '70', `commentaires` = 'Nom du site N°6' WHERE `nom` = 'Multisites-site6';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '80', `commentaires` = 'Nom du site N°7' WHERE `nom` = 'Multisites-site7';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '90', `commentaires` = 'Nom du site N°8' WHERE `nom` = 'Multisites-site8';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '100', `commentaires` = 'Nom du site N°9' WHERE `nom` = 'Multisites-site9';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '110', `commentaires` = 'Nom du site N°10' WHERE `nom` = 'Multisites-site10';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '25', `commentaires` = 'Adresses e-mails de la cellule planning du site N°1, séparées par des ;' WHERE `nom` = 'Multisites-site1-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '35', `commentaires` = 'Adresses e-mails de la cellule planning du site N°2, séparées par des ;' WHERE `nom` = 'Multisites-site2-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '45', `commentaires` = 'Adresses e-mails de la cellule planning du site N°3, séparées par des ;' WHERE `nom` = 'Multisites-site3-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '55', `commentaires` = 'Adresses e-mails de la cellule planning du site N°4, séparées par des ;' WHERE `nom` = 'Multisites-site4-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '65', `commentaires` = 'Adresses e-mails de la cellule planning du site N°5, séparées par des ;' WHERE `nom` = 'Multisites-site5-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '75', `commentaires` = 'Adresses e-mails de la cellule planning du site N°6, séparées par des ;' WHERE `nom` = 'Multisites-site6-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '85', `commentaires` = 'Adresses e-mails de la cellule planning du site N°7, séparées par des ;' WHERE `nom` = 'Multisites-site7-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '95', `commentaires` = 'Adresses e-mails de la cellule planning du site N°8, séparées par des ;' WHERE `nom` = 'Multisites-site8-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '105', `commentaires` = 'Adresses e-mails de la cellule planning du site N°9, séparées par des ;' WHERE `nom` = 'Multisites-site9-mail';";
$sql[] = "UPDATE `{$dbprefix}config` SET `ordre` = '115', `commentaires` = 'Adresses e-mails de la cellule planning du site N°1O, séparées par des ;' WHERE `nom` = 'Multisites-site10-mail';";