<?php

$sql[] = "ALTER TABLE `{$dbprefix}pl_poste_tab` ADD COLUMN IF NOT EXISTS `origin` INT(11) DEFAULT NULL, ADD COLUMN IF NOT EXISTS `updated` TINYINT(1) DEFAULT NULL, ADD COLUMN IF NOT EXISTS `updated_at` DATETIME DEFAULT SYSDATE();";
$sql[] = "ALTER TABLE `{$dbprefix}pl_poste_modeles_tab` ADD COLUMN IF NOT EXISTS `origin` INT(11) DEFAULT NULL, ADD COLUMN IF NOT EXISTS `adapted_at` DATETIME DEFAULT NULL, ADD COLUMN IF NOT EXISTS `updated_at` DATETIME DEFAULT SYSDATE();";
