<?php
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site1-position', 'enum', '1', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°1 dans les menus', 'Multisites', '27');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site2-position', 'enum', '2', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°2 dans les menus', 'Multisites', '37');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site3-position', 'enum', '3', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°3 dans les menus', 'Multisites', '47');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site4-position', 'enum', '4', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°4 dans les menus', 'Multisites', '57');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site5-position', 'enum', '5', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°5 dans les menus', 'Multisites', '67');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site6-position', 'enum', '6', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°6 dans les menus', 'Multisites', '77');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site7-position', 'enum', '7', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°7 dans les menus', 'Multisites', '87');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site8-position', 'enum', '8', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°8 dans les menus', 'Multisites', '97');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site9-position', 'enum', '9', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°9 dans les menus', 'Multisites', '107');";
$sql[] = "INSERT INTO `{$dbprefix}config` (`nom`, `type`, `valeur`, `valeurs`, `commentaires`, `categorie`, `ordre`) VALUES ('Multisites-site10-position', 'enum', '10', '1,2,3,4,5,6,7,8,9,10', 'Position du sites N°10 dans les menus', 'Multisites', '117');";